spring.application.name=cadastro

spring.datasource.url=jdbc:postgresql://db.grrrgmrdzcgbgfphaghx.supabase.co:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres
spring.datasource.password=merCejeQ4ttcdmSj

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false